### PR TITLE
Windows support + async compress/decompress

### LINKED ISSUE #3: Installing bode-jpeg-turbo windows server 2012 r2
Hi sorccu

I'm building the stf project on windows server 2012, I think I'm on a good point on this.

Anyways, the only problem I'm still facing is with the node-jpeg-turbo module

I'm installing it via npm install -g stf --msvs_version=2013

Everything installs but this module, it throws me this error:

yasm: Error FATAL: Unable to open include file 'jsimdcfg.inc'

I'm using yasm version 1.3.0 for windows x64

It is already on C:\windows\yasm

Changed yasm name from yasm-1.3.0-x64 to simply yasm.exe, added to win PATH.

I can run it from cmd terminal, only when I'm installing node-jpeg-turbo module it throws that error

Any ideas?

Thank You in advance!

### PR DESCRIPTION
**Pull request by empee**
Tested on Windows 8.1 (32bit) and Windows 10 (64bit) and it will compile as long as node +  yasm + pre-gyp (+ all the requirements for it) are working right. (So it might fix #3 )

Also added async compress/decompress for convenience, didn't update the readme.md for those yet.

Also updated the libjpeg-turbo submodule to 1.4.2

### CODE REVIEW

**Comment by sorccu** [comment]
Wow, that's amazing! Any chance you could try to make the Appveyor integration work as well?

I would like to see a few changes. First, the API methods don't match the filenames right now. Of course that was already the situation, I had planned on adding both async and sync versions to the same file. In this case since everything's separate, it would make sense to rename `<method>.cc` files to `<method>Sync.cc`, and the `<method>Async.cc` files to `<method>.cc`.

Second, it's kind of a pain to have almost the same code twice. Would you happen to have the knowledge to make the sync API just wrap the async API? That way the binaries would be smaller, and more importantly, only one place would need to be changed.

File: deps/include/jconfigint.h [hunk 1]
```diff
@@ -0,0 +1,9 @@
+#ifndef INLINE
+#if defined(__GNUC__)
```
Comment (sorccu) [inline deps/include/jconfigint.h:2]: Does this branch cover LLVM too?

Comment (sorccu) [inline deps/include/jconfigint.h:2]: Perhaps it would be best if we just made the `__GNUC__` branch the default else branch.

File: deps/libjpeg-turbo.gyp [hunk 2]
```diff
@@ -117,13 +117,14 @@
         'HAVE_UNISTD_H=1',
         'HAVE_UNSIGNED_CHAR=1',
         'HAVE_UNSIGNED_SHORT=1',
-        'INLINE=inline __attribute__((always_inline))',
         'JPEG_LIB_VERSION=62',
-        'LIBJPEG_TURBO_VERSION="1.4.1"',
+        'LIBJPEG_TURBO_VERSION="1.4.2"',
```
Comment (sorccu) [inline deps/libjpeg-turbo.gyp:121]: Could you also change the BUILD define to match the libjpeg-turbo commit. Looks like it should be 8f1c0a681cd34e8e80ba7b06f356d6080a7172c9.

File: src/exports.h [hunk 3]
```diff
@@ -11,6 +11,10 @@
 #define TJFLAG_FASTDCT 0
 #endif
 
+#ifdef DEFAULT_QUALITY
+#undef DEFAULT_QUALITY
```
Comment (sorccu) [inline src/exports.h]: Perhaps we would prefix our defines instead of doing this. Think you could update the code?

Comment (sorccu) [inline src/exports.h]: Maybe `NJT_DEFAULT_QUALITY` instead of just `DEFAULT_QUALITY`. Same for subsampling.

File: deps/include/jconfigint.h (hunk 1 above)
Comment (sorccu) [inline deps/include/jconfigint.h:2]: Looks like it clang defines it as well.

**Comment by sorccu** [comment]
If the sync wrapper seems difficult to do, perhaps we should split this PR into two PRs. First Windows support, then async.

File: deps/include/jconfigint.h (hunk 1 above)
Comment (empee) [inline deps/include/jconfigint.h:2]: The jconfigint.h is pretty much what libjpeg-turbo generates on my mac and since it seemed to work for debian+osx+windows I just assumed it's probably pretty good..
At least it worked better (and wider) than the define in the .gyp

File: deps/libjpeg-turbo.gyp (hunk 2 above)
Comment (empee) [inline deps/libjpeg-turbo.gyp:121]: Will do

File: src/exports.h (hunk 3 above)
Comment (empee) [inline src/exports.h]: I already thought of this, but since I was already changing quite a bit I didn't want to touch something that I could get around

**Comment by empee** [comment]
I already have an idea how to do the async/sync code much cleaner without the need to repeat too much code..

Also about the appveyor, I'll see if I can figure out how to get it working, looked at their documentation and the node.js part should be pretty simple, the yasm.. Well, lets see.

I'll do another PR later when I get more of it sorted out, shouldn't be more than a day or two..

**Comment by empee** [comment]
Couple of questions / ideas:
-Is there a reason why we return bpp and subsampling? User defines format -> they know bpp already and subsampling is an int so it wont tell anyone much (unless you plan to pass it back to compress)
-Is options really necessary? What if we defaulted to rgba (what canvas etc. use)?

Dropping the bpp and subsampling return would just make the code a lot more clean and auto selecting format would make it also a bit simpler "pass it data and callback -> receive buffer, width, height, size" or in sync version "call it with data, receive object with buffer, width, height, size"

Also I have now combined sync/async, there's still a bit of repeated code but not as much as there was, mainly dealing with the "how to call decompress/return data to user"

**Comment by sorccu** [comment]
I wouldn't mind adding default options if none are passed, as long as you're still able to set them if you want. I'm not sure if I get how reducing the number of returned values would clean up the code, since the values are needed in calculations or need to be given to jpeg-turbo anyway. What's the difference between returning 4 values vs 6 values?

**Comment by empee** [comment]
You'll see.. Has to do with pointers & more pointers.. Don't need to pass bpp & subsampling around if they are just used by the decompress and not returned, just need to pass the (optional) format there and it can figure out the rest itself.

Btw. one question I forgot to ask, why are we returning data if user provides their own buffer? Isn't that kind of redundant since they kind of expect their own buffer to hold the data?

**Comment by sorccu** [comment]
Behaving the same way in both cases makes it easier to start or stop using a preallocated buffer, since you only need to change pretty much one line and don't have to change how you deal with the return value.

**Comment by empee** [comment]
I'll start poking the AppVeyor now .. Got other stuff done.. As a bonus I added callback support to bufferSize as well

**Comment by empee** [comment]
This is getting kind of ridiculous, everything else but x86 node 4.x compiles..

**Comment by empee** [comment]
There it is.. "All checks have passed" .. The 4.4.5 on x86 fails for some odd reason, works on x64 thou..

**Comment by sorccu** [comment]
Really sorry that it took so long but the PR has now been merged. Reason being that I splurged on a Parallels and Win 10 Pro license and was actually able to try it out.

I'll be making some more changes after this but overall it was quite flawless.

I'd like to offer you $50 from the [OpenSTF](https://github.com/openstf/stf) donation fund for such an awesome contribution. Please send your PayPal email address to simo @ {the name of that GitHub organization} .io, or if not, feel free to recommend some other method.
